### PR TITLE
SwaggerGen - Support required fields for non-nullable

### PR DESCRIPTION
**Pull request by shainegordon**
Given a command like so:

```
public class CreateProductCommand : IRequest<Guid>, ICommand
{
    public CreateProductCommand(string name, bool isActive)
    {
        Name = name;
        IsActive = isActive;
    }

    public string Name { get; set; }
    public bool IsActive { get; set; }
}
```

when exposed as an API endpoint, by default, the swagger document component schema will look as follows

```
    "Products.Application.Products.CreateProductCommand": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "isActive": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
```

This however is not 100% correct, because as you can see, it is saying that `name` is `nullable`

This PR will enable swagger to output the following, assuming that the new module setting "Mark non-nullable fields as required":

```
    "Products.Application.Products.CreateProductCommand": {
        "required": [
          "isActive",
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "isActive": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
```

As we can see, it is now marked `isActive` and `name` as required.

This is extremely useful when generating API clients from OpenAPI Specification documents, as it will create the correct types in the target language

e.g.

```
export interface CreateProductCommand {
    name: string;
    isActive: boolean;
}
```

instead of 
```
export interface CreateProductCommand {
    name?: string | undefined;
    isActive?: boolean | undefined;
}
```

### CODE REVIEW

**Comment by JonathanLydall** [comment]
Thanks @shainegordon, this looks great.

How would you feel if we changed it so that this wasn't an option and would _always_ apply provided nullable types are enabled for the C# project?

**Comment by shainegordon** [comment]
> Thanks @shainegordon, this looks great.
> 
> How would you feel if we changed it so that this wasn't an option and would _always_ apply provided nullable types are enabled for the C# project?

I think that is a great default, and the only reason I made it "opt in", was to ensure backwards compatibility for anyone who is already using the openapi spec files for existing tooling/postman

**Comment by JonathanLydall** [comment]
Great, we'll discuss as a team early next week regarding prioritization and finalization of the improvement, including whether or not this will be an option.

**Comment by shainegordon** [comment]
@JonathanLydall I am not sure where this PR is sitting, but because it is still open, I have added another enhancement, via a new setting called "Use simple schema IDs"

This will do the following.

Instead of your Open API Spec listing component ID's like so:

```
"$ref": "#/components/schemas/Realm.SshKeyManagement.Api.Controllers.RegisterDto"

"$ref": "#/components/schemas/Realm.SshKeyManagement.Application.Common.Pagination.PagedResult`1[[Realm.SshKeyManagement.Application.Clients.Crud.ClientDto, Realm.SshKeyManagement.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
```

It will instead output like

```
"$ref": "#/components/schemas/RegisterDto"
"$ref": "#/components/schemas/PagedResultOfClientDto"
```


This is all in the name of simplified code generation capabilities when generating API clients

**Comment by JonathanLydall** [comment]
> @JonathanLydall I am not sure where this PR is sitting, but because it is still open, I have added another enhancement, via a new setting called "Use simple schema IDs"
> 
> This will do the following.
> 
> Instead of your Open API Spec listing component ID's like so:
> 
> ```
> "$ref": "#/components/schemas/Realm.SshKeyManagement.Api.Controllers.RegisterDto"
> 
> "$ref": "#/components/schemas/Realm.SshKeyManagement.Application.Common.Pagination.PagedResult`1[[Realm.SshKeyManagement.Application.Clients.Crud.ClientDto, Realm.SshKeyManagement.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
> ```
> 
> It will instead output like
> 
> ```
> "$ref": "#/components/schemas/RegisterDto"
> "$ref": "#/components/schemas/PagedResultOfClientDto"
> ```
> 
> This is all in the name of simplified code generation capabilities when generating API clients

I'm looking at this PR now and this addition is also great. We generate the more verbose names to avoid possible conflicts, but understand that some people would prefer the simpler names where they themselves can make sure there is no conflict.

**Comment by shainegordon** [comment]
> > @JonathanLydall I am not sure where this PR is sitting, but because it is still open, I have added another enhancement, via a new setting called "Use simple schema IDs"
> > This will do the following.
> > Instead of your Open API Spec listing component ID's like so:
> > ```
> > "$ref": "#/components/schemas/Realm.SshKeyManagement.Api.Controllers.RegisterDto"
> > 
> > "$ref": "#/components/schemas/Realm.SshKeyManagement.Application.Common.Pagination.PagedResult`1[[Realm.SshKeyManagement.Application.Clients.Crud.ClientDto, Realm.SshKeyManagement.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will instead output like
> > ```
> > "$ref": "#/components/schemas/RegisterDto"
> > "$ref": "#/components/schemas/PagedResultOfClientDto"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is all in the name of simplified code generation capabilities when generating API clients
> 
> I'm looking at this PR now and this addition is also great. We generate the more verbose names to avoid possible conflicts, but understand that some people would prefer the simpler names where they themselves can make sure there is no conflict.

The conflict point is very valid.

And I kind of also like the verbose names, but the default way it generates generics is not great

e.g. "$ref": "#/components/schemas/Realm.SshKeyManagement.Application.Common.Pagination.PagedResult`1[[Realm.SshKeyManagement.Application.Clients.Crud.ClientDto, Realm.SshKeyManagement.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"


let me think how we can possibly solve these things, while still allowing for the verbose version

**Comment by JonathanLydall** [comment]
> The conflict point is very valid.
> 
> And I kind of also like the verbose names, but the default way it generates generics is not great
> 
> e.g. "$ref": "#/components/schemas/Realm.SshKeyManagement.Application.Common.Pagination.PagedResult`1[[Realm.SshKeyManagement.Application.Clients.Crud.ClientDto, Realm.SshKeyManagement.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
> 
> let me think how we can possibly solve these things, while still allowing for the verbose version

@shainegordon, I see, and having seen the "Friendly" identifier you did I understand completely.

In the meantime, I have pushed a [commit](https://github.com/IntentArchitect/Intent.Modules.NET/commit/d9eba79a55e428ade1b69ff8e1f2252fd3d1a187) where I've made some updates to your work.

Just some comments on the changes I've made:

- We didn't want to use the `Swashbuckle.Core` NuGet package as it's compiled for [.NET Framework only](https://www.nuget.org/packages/Swashbuckle.Core#supportedframeworks-body-tab).
- For "friendly" identifier generation, I've made a method instead.

Otherwise, I expect my changes should be pretty obvious.

Also of note is that I could very easily adapt the friendly name generation method to return a fully qualified name but otherwise being more "friendly", although generic types would land up being quite long still.

**Comment by JonathanLydall** [comment]
And I've now also added this commit which adds test applications and fixes a missing semi-colon:
https://github.com/IntentArchitect/Intent.Modules.NET/commit/40187ccef875d09394e68599fd5fd4de2403e735

**Comment by shainegordon** [comment]
> And I've now also added this commit which adds test applications and fixes a missing semi-colon: [40187cc](https://github.com/IntentArchitect/Intent.Modules.NET/commit/40187ccef875d09394e68599fd5fd4de2403e735)

awesome, nice changes, looking forward to this being part of core

**Comment by JonathanLydall** [comment]
This PR has been merged into a feature branch in this repository and a [PR to merge from the feature branch has been created](https://github.com/IntentArchitect/Intent.Modules.NET/pull/7).

**Pull request merged**
