### PR TITLE
Feature/dotnet8

### PR DESCRIPTION
**Pull request by shainegordon**
this enables setting your projects to use .net 8

### CODE REVIEW

**Comment by shainegordon** [comment]
I've only updated 2 module versions, so that I can push them to our local registry temporarily.

Intent.VisualStudio.Projects -> 3.4.2-pre.0
Intent.AspNetCore.Versioning -> 1.0.4-pre.0


The other modules will need to be versioned

**Comment by shainegordon** [comment]
some other warning as well that I wasn't able to figure out, but isn't blocking at this moment

image

**Comment by JonathanLydall** [comment]
Thank you @shainegordon!

I'm merging into branch on our repository to do additional work such as add tests, etc, on our side.

**Comment by JonathanLydall** [comment]
Hi @shainegordon, these changes have now been merged into our `development` branch.

Aside from ensuring test coverage, I also improved the `Intent.Common.CSharp` module to make it easy to get the "maximum" .NET5+ version of a project so that instead of throwing an exception as they did before, they will instead now still run (just without updating NuGet versions) when the next version of .NET comes out.

If you're interested, you can see commit 581f72b0def0e034bc6a8b23bf398a935e22501f.

Please also note that these updates will require at least version 4.1.0 beta of Intent Architect itself to be used.

Thank you again.

**Pull request merged**
