### PR TITLE
[Bug]: 5975902171 - Blazor Server module generating malformed start up file code.

### PR DESCRIPTION
**Pull request by stephanjohnson**
The most significant changes include the update of the `HostWiringFactoryExtension.cs` file to include additional namespaces and the refactoring of the `RegisterStartup` method in the same file. The `Intent.Blazor.Server.imodspec` file and the `Intent.Modules.Blazor.Server.csproj` file have also been updated to change the versions.

1. The `HostWiringFactoryExtension.cs` file has been updated to include additional namespaces for `System.Threading`, `Intent.Modules.Common.CSharp.AppStartup`, `Intent.Modules.Common.CSharp.DependencyInjection`, and `Intent.Modules.Common.Templates`. This change allows the file to access classes and methods from these namespaces without needing to use their fully qualified names.

2. The `RegisterStartup` method in `HostWiringFactoryExtension.cs` has been refactored to use the `IAppStartupTemplate` interface instead of the `ICSharpFileBuilderTemplate` interface. This change simplifies the method by using the `ConfigureServices`, `ConfigureApp`, and `ConfigureEndpoints` methods of the `StartupFile` property of the `IAppStartupTemplate` instance, instead of manually finding and modifying methods in the `CSharpFile` property.

3. The `Intent.Blazor.Server.imodspec` file has been updated to change the version from `1.0.0` to `1.0.1-pre.0`. This change indicates a pre-release version of the software, which may contain new features or bug fixes that are not yet fully tested.

4. The `Intent.Modules.Blazor.Server.csproj` file has been updated to change the versions of the `Intent.Modules.Common` and `Intent.Modules.Common.CSharp` packages from `3.4.3` and `3.3.37` to `3.5.0` and `3.4.0` respectively. This change updates the dependencies of the project to use the latest versions of these packages.

### CODE REVIEW

**Comment by JonathanLydall** [comment]
Hi @stephanjohnson,

Thanks, this looks good in principal, we do however also need test cases in the `Tests/Intent.Modules.NET.Tests.isln` solution covering the following 3 scenarios (that I can think of):

- Minimal hosting model with top level statements
- Minimal hosting model without top level statements
- Without minimal hosting model (i.e. startup.cs)

You will need to cover each case in a separate application, I know we have a `MinimalHostingModel` application which can cover the one scenario. `CleanArchitecture.TestApplication` can probably cover the `Startup.cs` scenario and I'm not sure about the last scenario, perhaps we should make a `MinimalHostingModel.TopLevelStatements` app.

To configure top level statements and minimal hosting model, you use the settings on the project in the VS designer:

image

**Comment by stephanjohnson** [comment]
Will ensure those are created

**Comment by stephanjohnson** [comment]
Ok, so here are the tests that I think we will need to be confident that this works:

~~Clean Architecture with Blazor Server~~
~~Clean Architecture without Blazor Server~~
~~Clean Architecture Top Level Statements with Blazor Server~~
~~Clean Architecture Top Level Statements without Blazor Server~~
~~Clean Architecture, Minimal Hosting with Blazor Server~~
~~Clean Architecture, Minimal Hosting without Blazor Server~~
~~Clean Architecture, Minimal Hosting Top Level Statements with Blazor Server~~
~~Clean Architecture, Minimal Hosting Top Level Statements without Blazor Server~~

Some of these (the ones without Blazor Server) probably already exists, I am going through the list of tests now. Would appreciate your feedback on this @JonathanLydall.

~~PS: What about the Dapr project types?~~

See comment below

**Comment by stephanjohnson** [comment]
After a discussion with @JonathanLydall and @joelsteventurner we have determined that three projects are enough to test the fix and the Blazor.Server module. They are:

1. Blazor.Server
2. Blazor.Server.MinimalHosting
3. Blazor.Server.MinimalHosting.TopLevelStatements

These projects have been added to the tests and are part of this PR in this [commit](https://github.com/IntentArchitect/Intent.Modules.NET/pull/15/commits/e0cf561dff7334d644e0b63421cf0effabf161dd)

**Pull request merged**
